VERBOSE: True

MODEL:
  SESSION: 'DHAN-SHR'
  INPUT: 'specular'
  TARGET: 'diffuse'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 100
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  SEED: 3407
  WANDB: False

TRAINING:
  VAL_AFTER_EVERY: 1
  PS_W: 256
  PS_H: 256
  TRAIN_DIR: './dataset/train/' # path to training data
  VAL_DIR: './dataset/val/'     # path to validation data
  SAVE_DIR: './checkpoints/'          # path to save models
  ORI: False
  LOG_FILE: 'training.txt'

TESTING:
  WEIGHT: './checkpoints/latest.pth'
  TEST_DIR: './dataset/test/'     # path to testing data
  ORI: True
  SAVE_IMAGES: True
  RESULT_DIR: './results/'
  LOG_FILE: 'testing.txt'

LOG:
  LOG_DIR: './log/'